### ISSUE TITLE
After initializated auth extension, edgedb ui stop working on the nuxt devtools

### ISSUE THREAD

**Issue by ivanparramartinez** [Tahul/nuxt-edgedb#28]
Hi, I've enabled the auth extension, but, after that the ui of edgedb stopped working. I can't understand why. This is a screenshot.
![Captura de pantalla 2024-06-06 a la(s) 12 43 53 p  m](https://github.com/Tahul/nuxt-edgedb/assets/16830391/418bb25c-cf1c-40dd-a8ae-7c1bf4ac7ac2)

**Comment by Tahul** [comment]
Hey there; I just tried `^0.0.48` on a fresh project and it works perfectly fine.

Could you let me know if you still have the issue?
